name: Provision GCP VM and Run DXToolkit

on:
  workflow_dispatch: # You can also use push or PR triggers

jobs:
  terraform:
    name: Terraform Provisioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  dxtoolkit:
    name: Run DXToolkit
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl unzip wget openssh-client

      - name: Install DXToolkit
        run: |
          wget https://github.com/delphix/dxtoolkit/archive/refs/heads/master.zip
          unzip master.zip
          mv dxtoolkit-master dxtoolkit

      - name: Setup SSH Key for Remote Execution (optional)
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Run DXToolkit Command (Local or Remote)
        run: |
          cd dxtoolkit
          # Option 1: Run from runner (ensure Delphix Engine is publicly accessible)
          perl dx_get_vdb_env.pl -d ${{ secrets.DELPHIX_ENGINE_IP }} -u ${{ secrets.DELPHIX_USERNAME }} -p ${{ secrets.DELPHIX_PASSWORD }}

          # Option 2: SSH into VM and run remotely
          # ssh -o StrictHostKeyChecking=no -i private_key.pem your-user@${{ secrets.GCP_VM_IP }} "cd /home/your-user/dxtoolkit && perl dx_get_vdb_env.pl -d ..."

